package handlers

import (
	"net/http"

	"github.com/auroratechnologies/mux"
)

// Router returns a mux router with the routes supported by the audit service
// It is generated by a method to faciliate testing
func Router() *mux.Router {
	r := mux.NewRouter()

	r.HandleFunc("/", Index).Methods("GET")

	r.HandleFunc("/check", PerformCheck).Methods("POST")

	r.PathPrefix("/static/").Handler(http.StripPrefix("/static/",
		http.FileServer(http.Dir("static/"))))

	return r
}
