package handlers

import (
	"crypto/md5"
	"io"
	"log"
	"net/http"

	"github.com/auroratechnologies/mux"
	"github.com/twrobel3/UBC-PoC/models"
)

// Router returns a mux router with the routes supported by the audit service
// It is generated by a method to faciliate testing
func Router() *mux.Router {
	checker, err := NewChecker("CA/rootCA", func(buyer models.Buyer) bool {
		h := md5.New()
		io.WriteString(h, buyer.SSN)
		hash := h.Sum(nil)
		return hash[0] > 127 // Randomly (but consistently) reject/approve people, for demo purposes
	})
	if err != nil {
		// Cannot continue without the CA working
		log.Fatal(err)
	}

	r := mux.NewRouter()

	r.HandleFunc("/", Index).Methods("GET")

	r.HandleFunc("/check", checker.PerformCheck).Methods("POST")

	r.PathPrefix("/static/").Handler(http.StripPrefix("/static/",
		http.FileServer(http.Dir("static/"))))

	return r
}
